MultiApp/Models/Persona.cs
namespace AdapterWeb.Models
{
    public class Persona
    {
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    }
}

MultiApp/Controllers/PersonaController.cs
using AdapterWeb.Models;
using BuilderWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Net.Http.Headers;
using System.Runtime.ConstrainedExecution;
using System.Security.Cryptography.Xml;
using Newtonsoft.Json;
using System.Text;
using MultiApp.Models;

namespace AdapterWeb.Controllers
{
    public class PersonaController : Controller
    {
        public async Task<IActionResult> Index()
        {
            IList<Persona> per;
            string cadena = "";
            try
            {
                using (var client = new System.Net.Http.HttpClient())
                {
                    var request = new System.Net.Http.HttpRequestMessage();
                    request.RequestUri = new Uri("http://WebApi/api/persona");
                    //request.RequestUri = new Uri("https://localhost:49199/api/persona");

                    var response = await client.SendAsync(request);
                    var prs = await response.Content.ReadAsStringAsync();
                    cadena = prs.ToString();
                    var details = Newtonsoft.Json.JsonConvert.DeserializeObject<IEnumerable<Persona>>(prs);

                    per = details.ToList();
                }
                return View(per);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", new { message = "cadena: "+ cadena + "error:"+ e.Message + " " +e.InnerException });
            }
           
        }
        public ActionResult Error(string message)
        {
            var model = new ErrorModel();
            model.Error = message;
            return View(model); // make sure your error view is named as "Error". Else u need to specify the view name in the return command.
        }
        public async Task<IEnumerable<Persona>>OnGet()
        {
            using (var client = new System.Net.Http.HttpClient())
            {
                var request = new System.Net.Http.HttpRequestMessage();
              request.RequestUri = new Uri("http://WebApi/api/persona");
              // request.RequestUri = new Uri("https://localhost:49199/api/persona");

                var response = await client.SendAsync(request);
                var prs = await response.Content.ReadAsStringAsync();
                var details = Newtonsoft.Json.JsonConvert.DeserializeObject<IEnumerable<Persona>>(prs);

                return details;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormCollection form)
        {
            Persona prs = new Persona();
            prs.cedula = form["cedula"];
            prs.nombre = form["nombre"];
            prs.apellido = form["apellido"];
            prs.direccion = form["direccion"];
            prs.telefono = form["telefono"];
            
            await OnInsert(prs);

            Task<IEnumerable<Persona>> persona = OnGet();
            IList<Persona> per = persona.Result.ToList();
            return View(per);
        }

        public async Task<bool> OnInsert(Persona persona)
        {
            bool rtn = true;
           
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(persona), Encoding.UTF8, "application/json");

               // using (var response = await httpClient.PostAsync("https://localhost:49165/api/persona", content))
                using (var response = await httpClient.PostAsync("http://WebApi/api/persona", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    
                }
            }
            return rtn;
        }
    }
}

MultiApp/Views/Persona/Index.cshtml
@using AdapterWeb.Models
@model IList<Persona> 
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
                <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">PERSONA</h3>

                        @using (Html.BeginForm("Index", "Persona"))
                        {

                            <div class="row">
                                <div class="col-md-4 mb-4">

                                    <div class="form-outline">
                                        <h4 class="mb-4 pb-4 pb-md-0 mb-md-5">Persona</h4>
                                    </div>
                                </div>
                              
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Cedula</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="cedula">
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Nombre</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="nombre">
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Apellido</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="apellido">
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Direccion</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="direccion">
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">telefono</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="telefono">
                                </div>
                                <div class="col-md-4 mb-4">

                                    <div class="form-outline">
                                        <input class="btn btn-primary btn-lg" type="submit" value="REGISTRAR" />
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">

                                    <table class="table">
                                        <thead>
                                            <tr>
                                                @if (Model != null)
                                                {
                                                    <th scope="col"> CEDULA </th>
                                                    <th scope="col"> NOMBRE </th>
                                                    <th scope="col"> APELLIDO </th>
                                                    <th scope="col"> DIRECCION </th>
                                                    <th scope="col"> TELEFONO </th>
                                                }
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach(var item in Model)
                                            {
                                                <tr>
                                                    <td> @item.cedula</td>
                                                    <td> @item.nombre</td>
                                                    <td> @item.apellido</td>
                                                    <td> @item.direccion</td>
                                                    <td> @item.telefono</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div id="msgid">
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">

                                    Nataly Hernandez
                                    Geovanny Criollo
                                    17/11/2022
                                    AUTOMATIZACIÓN DE LOS PROCESOS DE SOFTWARE GRUPO - 2

                                    </div>
                                    </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(document).ready(function () {

    });
</script>