MultiApp/Models/factura.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MultiApp.Model
{
    public class factura
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int numero { get; set; }
        public DateTime fecha { get; set; }
        public decimal valor { get; set; }
        public string descripcion { get; set; }

    }
}

MultiApp/Controllers/FacturaController.cs
using AdapterWeb.Models;
using BuilderWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Net.Http.Headers;
using System.Runtime.ConstrainedExecution;
using System.Security.Cryptography.Xml;
using Newtonsoft.Json;
using System.Text;
using MultiApp.Models;
using MultiApp.Model;

namespace AdapterWeb.Controllers
{
    public class FacturaController : Controller
    {
        public async Task<IActionResult> Index()
        {
            IList<factura> fac;
            string cadena = "";
            try
            {
                using (var client = new System.Net.Http.HttpClient())
                {
                    var request = new System.Net.Http.HttpRequestMessage();
                    request.RequestUri = new Uri("http://WebApi/api/factura");
                   // request.RequestUri = new Uri("https://localhost:44383/api/factura");

                    var response = await client.SendAsync(request);
                    var fct = await response.Content.ReadAsStringAsync();
                    cadena = fct.ToString();
                    var details = Newtonsoft.Json.JsonConvert.DeserializeObject<IEnumerable<factura>>(fct);

                    fac = details.ToList();
                }
                return View(fac);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", new { message = "cadena: "+ cadena + "error:"+ e.Message + " " +e.InnerException });
            }
           
        }
        public ActionResult Error(string message)
        {
            var model = new ErrorModel();
            model.Error = message;
            return View(model); // make sure your error view is named as "Error". Else u need to specify the view name in the return command.
        }
        public async Task<IEnumerable<factura>>OnGet()
        {
            using (var client = new System.Net.Http.HttpClient())
            {
                var request = new System.Net.Http.HttpRequestMessage();
              request.RequestUri = new Uri("http://WebApi/api/factura");
              // request.RequestUri = new Uri("https://localhost:44383/api/factura");

                var response = await client.SendAsync(request);
                var fct = await response.Content.ReadAsStringAsync();
                var details = Newtonsoft.Json.JsonConvert.DeserializeObject<IEnumerable<factura>>(fct);

                return details;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormCollection form) 
        {
            factura fcr = new factura();
            fcr.fecha = Convert.ToDateTime(form["fecha"]);
            fcr.descripcion = form["descripcion"];
            fcr.valor = Convert.ToDecimal(form["valor"]);

            await OnInsert(fcr);

            Task<IEnumerable<factura>> factura = OnGet();
            IList<factura> fct = factura.Result.ToList();
            return View(fct);
        }

        public async Task<bool> Delete(string id)
        {
            bool rtn = false;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://WebApi/api/");

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("factura/" + id.ToString());
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return true;
                }
            }


            return rtn;
        }

        public async Task<bool> OnInsert(factura Factura)
        {
            bool rtn = true;
           
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(Factura), Encoding.UTF8, "application/json");

                //using (var response = await httpClient.PostAsync("https://localhost:44383/api/factura", content))
               using (var response = await httpClient.PostAsync("http://WebApi/api/factura", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return rtn;
        }

        [HttpGet]
        public async Task<IActionResult> eliminar(string codigo)
        {
            await Delete(codigo);

            Task<IEnumerable<factura>> factura = OnGet();
            IList<factura> fct = factura.Result.ToList();
            return View("index",fct);
        }
    }
}

MultiApp/Views/Factura/Index.cshtml
@using MultiApp.Model
@model IList<factura>
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
                <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Factura</h3>

                        @using (Html.BeginForm("Index", "Factura"))
                        {

                            <div class="row">
                                <div class="col-md-4 mb-4">

                                    <div class="form-outline">
                                        <h4 class="mb-4 pb-4 pb-md-0 mb-md-5">Factura</h4>
                                    </div>
                                </div>
                              
                            </div>
                            <div class="row">
                                <div class="form-group">w   
                                    <label for="exampleFormControlInput1">Fecha</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="fecha">
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Valor</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="valor">
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Detalle</label>
                                    <input type="text" class="form-control" id="exampleFormControlInput1" name="descripcion">
                                </div>
                                <div class="col-md-4 mb-4">

                                    <div class="form-outline">
                                        <input class="btn btn-primary btn-lg" type="submit" value="REGISTRAR" />
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">

                                    <table class="table">
                                        <thead>
                                            <tr>
                                                @if (Model != null)
                                                {
                                                    <th scope="col"> NUMERO </th>
                                                    <th scope="col"> FECHA </th>
                                                    <th scope="col"> DETALLE </th>
                                                    <th scope="col"> VALOR </th>
                                                    <th scope="col"> ELIMINAR </th>
                                                }
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach(var item in Model)
                                            {
                                                <tr>
                                                    <td> @item.numero</td>
                                                    <td> @item.fecha</td>
                                                    <td> @item.descripcion</td>
                                                    <td> @item.valor</td>
                                                    <td>
                                                        <a href="@Url.Action("eliminar", "Factura", new {codigo=item.numero})">
                                                            <span>Eliminar</span>
                                                        </a>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div id="msgid">
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">

                                    Nataly Hernandez
                                    Geovanny Criollo
                                    20/11/2022
                                    AUTOMATIZACIÓN DE LOS PROCESOS DE SOFTWARE GRUPO - 2

                                    </div>
                                    </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(document).ready(function () {

    });
</script>